create table customer_1(
customer_id int generated by default as identity primary key,
customer_name varchar2(255),
customer_age real constraint cons_chech_age check (customer_age>12),
customer_gender char(50),
constraint con_cust2_uniq unique(customer_name)
);

insert into customer_1 (customer_name,customer_age,customer_gender) values('arif',13,'male');
insert into customer_1 (customer_name,customer_age,customer_gender) values('reyhan',16,'female');
insert into customer_1 (customer_name,customer_age,customer_gender) values('natiq',17,'male');
insert into customer_1 (customer_name,customer_age,customer_gender) values('eli',15,'male');
insert into customer_1 (customer_name,customer_age,customer_gender) values('natevan',19,'female');

delete customer_1 where customer_age=16 or customer_age=19; // delete where sertinden istifade ede bilir
truncate table customer_1; //truncate bele bir sey yoxdur

delete customer_1; // cedveli bloklayb daha sonra setir-setir silir
truncate table customer_1; // cedveli umumi olaraq silib yeniden yaradir

delete customer_1; //sildiyi her bir setirin ayri ayriligda logun saxlayr
truncate table customer_1; // lakin truncatede umumi cedvelin silindiyi logu saxlsyr

delete customer_1; //DML aiddir
truncate table customer_1; //DDL aiddir

delete customer_1; // silmek ucun delete permissiona ehtyac var
truncate table customer_1; // en azi alter permission olmalidir

delete customer_1;
insert into customer_1 (customer_name,customer_age,customer_gender) 
values ('ramiz',20,'male4'); // cedveli delete edib yeni setir elave eledikde ID nomresi qaldigi yerden davam edir

truncate table customer_1; // table seviyyesinde isleyir
delete customer_1; // data seviyyesinde isleyr

select * from customer_1;
drop table customer_1;